# Generated by Django 4.2.4 on 2023-08-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0007_alter_veiculo_cor_alter_veiculo_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="descricao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="veiculos",
                to="models.acessorio",
            ),
        ),
    ]
