# Generated by Django 4.2.4 on 2023-08-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0008_alter_veiculo_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acessorio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
