# Generated by Django 4.2.4 on 2023-08-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0009_alter_acessorio_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="descricao",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="descricao",
            field=models.ManyToManyField(to="models.acessorio"),
        ),
    ]
